# main site metadata and titles
site_name: RCPCH Epilepsy 12 - Documentation
site_description: RCPCH Epilepsy 12 - Documentation Site
site_author: The Royal College of Paediatrics and Child Health
site_url: https://docs.epilepsy12.rcpch.ac.uk

# copyright information which is shown in the footer
copyright: Copyright &copy; 2022 Royal College of Paediatrics and Child Health (RCPCH)

# these lines configure the 'GitHub repo' widget on the top right
repo_url: https://github.com/rcpch/epilepsy12-documentation
repo_name: rcpch/epilepsy12-documentation
edit_uri: blob/live/docs

# `mkdocs serve` serves the documentation at custom port (to avoid clashing with other services we commonly run)
dev_addr: "127.0.0.1:8001"

# theme settings, fonts, colours
theme:
  name: material
  #custom_dir: rcpch-theme
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.expand
    # - toc.integrate

  palette:
    # Light mode only for now
      scheme: default

  font:
    text: Montserrat
    code: Roboto Mono

  # favicon: _assets/_images/dynamic-child-favicon.png
  logo: _assets/_images/rcpch_logo.png

# mkdocs plugins
plugins:
  - search
  - with-pdf:
      back_cover: true
        #cover_title: TITLE TEXT
        #cover_subtitle: SUBTITLE TEXT
        #custom_template_path: TEMPLATES PATH
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #render_js: true
        #headless_chrome_path: headless-chromium
      output_path: pdf/rcpch-epilepsy12-full-documentation.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #debug_html: true
        #show_anchors: true
        #verbose: true

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

# set extra CSS file
extra_css:
  - _assets/_stylesheets/extra.css

# footer links and variables
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rcpchtweets
    - icon: fontawesome/brands/github
      link: https://github.com/rcpch
      
nav:
  - Home: 'index.md'
  - Clinician User Guide:
    - 'clinician-users/clinician-user-guide.md'
  - Admin User Guide:
    - 'admin-users/admin-user-guide.md'
  - Development:
    - 'development/getting-started.md'
    - 'development/docker-setup.md'
    - 'development/documentation.md'
    - 'development/manual-setup.md'
    - 'development/code-style.md'
  - Legal:
    - 'legal/legal.md'
    - 'legal/license.md'
    - 'legal/privacy-notice.md'