# This Action builds the documentation site in mkdocs, and pushes it to the gh-pages branch, from where it is deployed
# GitHub pages is the backup site: https://rcpch.github.io/epilepsy12-documentation
# Azure Static Web Sites is the main site: https://epilepsy12docs.rcpch.tech/

name: build-and-deploy-to-gh-pages.yml
on:
  push:
    branches:
      - live
permissions:
  contents: write
jobs:
  build-and-deploy-to-gh-pages:
    env:
      ENABLE_PDF_EXPORT: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'live'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force # Output files are force-pushed to gh-pages branch
      
  deploy-gh-pages-branch-to-azure:
    env:
      ENABLE_PDF_EXPORT: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages' # Use the newly-built 'gh-pages' branch not the default 'live' branch
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_BUSH_03EE83F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
